version: '3.8'
services:
      
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: "${ENV_FILE:-.env}"
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - simplenest

networks:
  simplenest:
